export const FETCH_LOCATIONS = 'FETCH_LOCATIONS';
export const ADD_LOCATION = 'ADD_LOCATION';
export const REMOVE_LOCATION = 'REMOVE_LOCATION';
export const UPDATE_LOCATION = 'UPDATE_LOCATION';
export const ALPHABETIC_SORT = 'ALPHABETIC_SORT';
